name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule update --init --recursive
          
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gotification"
          heroku_email: "allen.ccccnm@gmail.com"
          usedocker: true
          docker_build_args: |
            VUE_APP_PUSHER_INSTANCE_ID
        env:
          VUE_APP_PUSHER_INSTANCE_ID: ${{secrets.PUSHER_INSTANCE_ID}}
            